version: "3.8"

services:
  web:
    container_name: frontend-dev
    image: frontend-dev
    build:
      args:
        PORT: 3000
        PROJECT_PATH: './frontend'
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 3000:3000

  api:
    container_name: backend-dev
    build:
      args:
        PORT: 4000
        PROJECT_PATH: './backend'

    volumes:
      - ./backend/src:/app/src
    environment:
      DB_URL: mongodb://db_jcc:27017
    ports:
      - 5500:4000

  db_jcc:
    image: mongo:latest
    ports: 
      - 27017:27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: